apiVersion: v1
kind: Service
metadata:
  name: shipping
  namespace: roboshop
  labels:
    project: roboshop
    tier: backend
    component: shipping
spec:
  selector:
    # Labels are used as selectors.
    project: roboshop
    tier: backend
    component: shipping
  ports:
  - protocol: TCP
    port: 8080           # Service Port
    targetPort: 8080     # Container Port