apiVersion: v1
kind: Service         # To find other nodes IP address in Cluster for data replication
metadata:
  name: redis-headless
  namespace: roboshop
  labels:
    project: roboshop
    tier: database
    component: redis
spec:
  clusterIP: None
  selector:
    # Labels are used as selectors.
    project: roboshop
    tier: database
    component: redis
  ports:
  - protocol: TCP
    port: 6379         # Service Port
    targetPort: 6379   # Container Port  
---
# Create multiple replicas of your pod. Always runs desired number of pods.
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  namespace: roboshop
  # These labels are replicaset labels reference
  labels:
    project: roboshop
    tier: database
    component: redis
spec:
  selector:
  # Using these labels, replicaset selects the pod.
    matchLabels:
      project: roboshop
      tier: database
      component: redis
  serviceName: "redis-headless"    # We should attach headless service
  # replicas: 3          # By default is 1
  replicas: 1
  # Pod definition
  template:
    metadata:
      labels:
        project: roboshop
        tier: database
        component: redis
    spec:
      containers:
      - name: redis
        image: redis:7.0
        volumeMounts:
        - name: redis
          mountPath: /data
  # Persistent Volume Claim (PVC) -> It is claiming that it needs Storage.
  volumeClaimTemplates:
  - metadata:
      name: redis
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "roboshop-ebs"
      resources:
        requests:
          storage: 1Gi
---
apiVersion: v1
kind: Service       # Used for Load Balancing
metadata:
  name: redis
  namespace: roboshop
  labels:
    project: roboshop
    tier: database
    component: redis
spec:
  selector:
    # Labels are used as selectors.
    project: roboshop
    tier: database
    component: redis
  ports:
  - protocol: TCP
    port: 6379          # Service Port
    targetPort: 6379    # Container Port