apiVersion: v1
kind: Service   # To find other nodes IP address in Cluster for data replication
metadata:
  name: mongodb-headless
  namespace: roboshop
  labels:
    project: roboshop
    tier: database
    component: mongodb
spec:
  clusterIP: None
  selector:
    # Labels are used as selectors.
    project: roboshop
    tier: database
    component: mongodb
  ports:
  - protocol: TCP
    port: 27017          # Service Port
    targetPort: 27017    # Container Port  
---
# Create multiple replicas of your pod. Always runs desired number of pods.
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
  namespace: roboshop
  # These labels are replicaset labels reference
  labels:
    project: roboshop
    tier: database
    component: mongodb
spec:
  selector:
  # Using these labels, replicaset selects the pod.
    matchLabels:
      project: roboshop
      tier: database
      component: mongodb
  serviceName: "mongodb-headless"    # We should attach headless service
  # replicas: 3          # By default is 1
  replicas: 1
  # Pod definition
  template:
    metadata:
      labels:
        project: roboshop
        tier: database
        component: mongodb
    spec:
      containers:
      - name: mongodb
        image: javeedmohd214/mongodb:1.4.0
        volumeMounts:
        - name: mongodb
          mountPath: /data/db
  # Persistent Volume Claim (PVC) -> It is claiming that it needs Storage.
  volumeClaimTemplates:
  - metadata:
      name: mongodb
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "roboshop-ebs"
      resources:
        requests:
          storage: 1Gi
---
apiVersion: v1
kind: Service           # Used for Load Balancing
metadata:
  name: mongodb
  namespace: roboshop
  labels:
    project: roboshop
    tier: database
    component: mongodb
spec:
  selector:
    # Labels are used as selectors.
    project: roboshop
    tier: database
    component: mongodb
  ports:
  - protocol: TCP
    port: 27017          # Service Port
    targetPort: 27017    # Container Port   