apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment
  namespace: roboshop
  # These labels are replicaset labels reference
  labels:
    project: roboshop
    tier: backend
    component: payment
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
  # Using these labels, replicaset selects the pod.
    matchLabels:
      project: roboshop
      tier: backend
      component: payment
  # This is Pod definition, Pod is subset of replicaset
  template:
    metadata:
      labels:
        project: roboshop
        tier: backend
        component: payment
    spec:
      containers:
      - name: payment
        image: "{{ .Values.deployment.imageName }}:{{ .Values.deployment.imageVersion }}"
        imagePullPolicy: Always       # Safe to pull everytime, there may be same version rebuilt and pushed.
        resources:
          # Soft limit
          requests:
            memory: "128Mi"
            cpu: "100m"
          # Hard limit
          limits:
            memory: "256Mi"
            cpu: "120m"
        # A readiness probe checks whether a container is ready to accept traffic. If it fails, K8s stops sending requests to that container.
        readinessProbe:
          # httpGet:
          #   path: /health
          #   port: 8080
          # To check whether the port is open/not
          tcpSocket:
            port: 8080
          failureThreshold: 2
          periodSeconds: 10
          initialDelaySeconds: 30       # Container will become available in 35 seconds.
        # A liveness probe checks whether a container is still running properly. If it fails, K8s restarts the container.
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          failureThreshold: 2
          periodSeconds: 10
          initialDelaySeconds: 30
        # envFrom is used in a Pod specifications to load all key–value pairs from a ConfigMap or Secret as environment variables into a container.
        envFrom:
        - configMapRef:
            name: payment